stages:
  - package-6.0.0
  - package-5
  - package-4
  - source
  - all

variables:
    URL: "https://thopiekar.eu:5443/cura-cad-integration/CuraBlenderPlugin.git"
    TESTFILE: "test.file"
    PACKAGE600: "package6"
    PACKAGE5: "package5"
    PACKAGE4: "package4"
    API4: "plugin4"
    SOURCE: "source"
    ALL: "all"

package-6.0.0-git:
  stage: package-6.0.0
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$PACKAGE600 --source=$URL --result=$TESTFILE
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

package-6.0.0-source:
  stage: package-6.0.0
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$PACKAGE600 --source=./source --result=$TESTFILE
  - rm -rf ./source
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

package-5-git:
  stage: package-5
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$PACKAGE5 --source=$URL --result=$TESTFILE
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

package-5-source:
  stage: package-5
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$PACKAGE5 --source=./source --result=$TESTFILE
  - rm -rf ./source
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

package-4-git:
  stage: package-4
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$PACKAGE4 --source=$URL --result=$TESTFILE
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

package-4-source:
  stage: package-4
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$PACKAGE4 --source=./source --result=$TESTFILE
  - rm -rf ./source
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

source-git:
  stage: source
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$SOURCE --source=$URL --result=$TESTFILE
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

source-source:
  stage: source
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$SOURCE --source=./source --result=$TESTFILE
  - rm -rf ./source
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

all-git:
  stage: all
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$ALL --source=$URL --result=$TESTFILE
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags

all-source:
  stage: all
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$ALL --source=./source --result=$TESTFILE
  - rm -rf ./source
  - if [[ ! -f $TESTFILE ]] ; then exit 1 ; fi
  only:
    - triggers
    - branches
    - tags
