stages:
  - package-6.0.0
  - plugin-5
  - source
  - all

variables:
    URL: "https://thopiekar.eu:5443/cura-cad-integration/CuraBlenderPlugin.git"
    TESTFILE: "test.file"
    SDK600: "package6"
    API5: "plugin5"
    API4: "plugin4"
    SOURCE: "source"
    ALL: "all"

package-6.0.0-git:
  stage: package-6.0.0
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$SDK600 --source=$URL --result=$TESTFILE
  - [[ -f $TESTFILE ]] || exit 1
  only:
    - triggers
    - branches
    - tags

package-6.0.0-source:
  stage: package-6.0.0
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$SDK600 --source=./source
  - rm -rf ./source
  only:
    - triggers
    - branches
    - tags

plugin-5-git:
  stage: plugin-5
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$API5 --source=$URL
  only:
    - triggers
    - branches
    - tags

plugin-5-source:
  stage: plugin-5
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$API5 --source=./source
  - rm -rf ./source
  only:
    - triggers
    - branches
    - tags

source-git:
  stage: source
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$SOURCE --source=$URL
  only:
    - triggers
    - branches
    - tags

source-source:
  stage: source
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$SOURCE --source=./source
  - rm -rf ./source
  only:
    - triggers
    - branches
    - tags

all-git:
  stage: all
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$ALL --source=$URL
  only:
    - triggers
    - branches
    - tags

all-source:
  stage: all
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $URL ./source --recurse-submodules
  - python3 ../cpo.py --create=$ALL --source=./source
  - rm -rf ./source
  only:
    - triggers
    - branches
    - tags
