stages:
  - package-6.0.0

variables:
    SOURCE: "https://thopiekar.eu:5443/cura-cad-integration/CuraBlenderPlugin.git"
    SDK600: "package6"
    API5: "plugin5"
    API4: "plugin4"

package-6.0.0-git:
  stage: package-6.0.0
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - python3 ../cpo.py --create=$SDK600 --source=$SOURCE
  only:
    - triggers
    - branches
    - tags

package-6.0.0-source:
  stage: package-6.0.0
  tags:
  - os:ubuntu,
  - package:python3
  - type:shell
  script:
  - cd tests
  - git clone $SOURCE ./source --recurse-submodules
  - python3 ../cpo.py --create=$SDK600 --source=./source
  only:
    - triggers
    - branches
    - tags
